apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-computing-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-computing-api
  template:
    metadata:
      labels:
        app: cloud-computing-api
    spec:
      containers:
        - name: cloud-computing-api
          image: docker.io/cloud-computing-api:latest
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-computing-api
  namespace: default
  labels:
    app: cloud-computing-api
spec:
  type: NodePort
  selector:
    app: cloud-computing-api
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 8080
